branches:
  - main

tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          release: patch
        - type: chore
          release: patch
        - breaking: true
          release: major

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
            hidden: false
          - type: fix
            section: "Bug Fixes"
            hidden: false
          - type: docs
            section: "Documentation"
            hidden: false
          - type: chore
            section: "Maintenance"
            hidden: false

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i "s/default: 'v[0-9]*\.[0-9]*\.[0-9]*'/default: 'v${nextRelease.version}'/g" action.yml
        sed -i "s/| \`version\` | Infer CLI version to install | No | \`v[0-9]*\.[0-9]*\.[0-9]*\` |/| \`version\` | Infer CLI version to install | No | \`v${nextRelease.version}\` |/g" README.md
        sed -i "s|inference-gateway/infer-action@v[0-9]*|inference-gateway/infer-action@v${nextRelease.major}|g" README.md

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - action.yml
        - README.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - CHANGELOG.md
