---
branches:
  - main

tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          release: patch
        - type: chore
          release: patch
        - breaking: true
          release: major

  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
            hidden: false
          - type: fix
            section: "Bug Fixes"
            hidden: false
          - type: docs
            section: "Documentation"
            hidden: false
          - type: chore
            section: "Maintenance"
            hidden: false

  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - CHANGELOG.md
